### ISSUE TITLE
Percent diff table is not showing the percentages

### ISSUE THREAD

**Issue by mnmehta** [distributed-system-analysis/pbench-dashboard#10]
![image](https://user-images.githubusercontent.com/30246802/76659896-d8e7dc00-6534-11ea-9359-6401a8f3dbc3.png)

**Comment by aquibbaig** [comment]
I'd like to take this up @gurbirkalsi

**Comment by aquibbaig** [comment]
Hi @mnmehta. I was looking into the issue. Is there any "steps to reproduce" in this issue that you could help me with to gather more context on this.

**Comment by portante** [comment]
Please re-open this issue if a reproducer is found.
