### ISSUE TITLE
Use server `/api/v1/endpoints` API to to auto-configure the Dashboard

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench-dashboard#107]
Improve dashboard deployment experience by using the Pbench server `/api/v1/endpoints` API instead of a hardcoded `endpoints.js` file built into the javascript bundle loaded on the server.

That way we can build one dashboard bundle and test it on staging and move it to production without having to change or rebuild the bundle.

_Originally posted by @portante in https://github.com/distributed-system-analysis/pbench-dashboard/issues/106#issuecomment-737425234_

**Comment by dbutenhof** [comment]
In some ways having `pbench` and `pbench-dashboard` as separate repositories makes coordination more difficult. We really need a `pbench` PR first to implement an API which can then be leveraged here. I'll clone this to start.
