### ISSUE TITLE
Clicking on "Dashboard" in sidebar opens up the private view

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#113]
I am not sure it is the desired behaviour but clicking on the "dashboard" link in the sidebar opens up the private view. Note that when we open the application for the first time, the "dashboard" link is active, meaning we are in the Controllers page.

**Comment by anishaswain** [comment]
@aquibbaig could you please add a screenshot of the bug you are talking about over here? It would be really helpful

**Comment by anishaswain** [comment]
@aquibbaig the routes will be fixed by the changes from #105 where we will add different routes for overview(private) and controllers/Dashboard(public) pages

**Comment by aquibbaig** [comment]
@anishaswain I see, so let's keep this issue as "Open" until we merge #105

**Comment by aquibbaig** [comment]
### Description

![dashboard-private](https://user-images.githubusercontent.com/26324376/102082370-d83fe700-3ddf-11eb-9981-a4d627f5a5e7.png)
