### ISSUE TITLE
Relay user specific data to the backend

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#119]
User-specific data such as favourite controllers, records or iterations are currently persisted across browser sessions via local storage, which is reflected once they open up their browser. We would want to save these records in the backend and fetching the same on to the dashboard.

**Comment by portante** [comment]
We'll need server side end-points to store user data.

**Comment by npalaska** [comment]
Discussed a while back here https://github.com/distributed-system-analysis/pbench/pull/2049
