### ISSUE TITLE
Forgot password mechanism on the frontend

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#122]
We would certainly need an implementation of "forgot password" workflow on the frontend and let our dashboard handle that. Some of these steps include the following:
- When the user clicks on forgot password option in the login page, he is taken to a route where he is prompted for username/email or both based on the validation that we will do on the backend.
- Backend generates a link which takes the user to the password recovery page for the actual account. (It is important to validate the authenticity of the link which is generated in the backend somehow).
- After the user recovers his password successfully, he will be taken to the login page, where he would log in with his new credentials

**Comment by portante** [comment]
Work started in #123.

**Comment by pravins** [comment]
Moving to Keycloak, feel free to reopen if any problem.
