### ISSUE TITLE
Table search autocomplete

### ISSUE THREAD

**Issue by gurbirkalsi** [distributed-system-analysis/pbench-dashboard#157]
During a discussion with @mnmehta, we identified a requirement for autocompleting search results when searching within the table component for allowing faster navigation.

**Comment by aquibbaig** [comment]
Hey Gurbir, do we want to implement something from scratch or use a plugin such as [Algolia](https://www.algolia.com/), also I'd like to pick this up.

**Comment by aquibbaig** [comment]
Right, we can just use `setGlobalFilter`, it doesn't create any UI jag with mock data, which may be a case when the table data source is high (probably), then we need to do some optimizations.
