### ISSUE TITLE
inconsistent results for e2e tests

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#178]
I noticed that casual.js generated namespaces sometimes can have the same key for different objects. That way, the Table component we have will be unable to sort the entries. We get inconsistency in terms of our tests, as a result, I have to re-rerun job multiple times, we should get a permanent fix for it (else dump the tests for sorting ascending or descending, keeping in mind that this function is already tested in react-table and should always work as expected)

**Comment by anishaswain** [comment]
@aquibbaig I don't think dumping the tests for sorting ascending or descending is a good idea. Instead we should try to have unique keys for a session somehow.
