### ISSUE TITLE
can't fetch from /api/v1 to fetch endpoints

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#194]
For testing with a real server, we need endpoints served at `/api/v1` to populate endpoints in the dashboard.

**Comment by dbutenhof** [comment]
Clarification: this involves supporting the `yarn start` mode of testing dashboard code *locally* with an npm server against a real remote Pbench server.

What does work now:

1. Testing locally against mocked data with `yarn start:mock`
2. Testing against a real Pbench server by deploying the dashboard `yarn build` package to a running server instance. (This will be easier once we have a containerized server.)

What doesn't work now:

1. `yarn start` local testing stands up an npm server responding on `localhost` which does not support the fetch to `/api/v1/endpoints` at `window.origin`.

The "fix" may be to figure out how to make `yarn start` stand up a minimal local nodeJS server that reads some environment variable pointing at a remote server and then responds to local `/api/v1/endpoints` queries by reflecting the `GET` to the designated remote server. From there, everything should work fine as the dashboard will direct subsequent server requests through `window.endpoints.api.xxx` which will be the full URLs returned by the real server.

I've created local nodeJS API code in UI class exercises, so this shouldn't be difficult; I'll just have to find time to do some searches to refresh my stale memories. 😁

Of course if someone with less stale memories of how to make this work were to feel inclined to try, I wouldn't object!

**Comment by aquibbaig** [comment]
@dbutenhof This can come into the part where we redesign the dashboard architecturally. Using some framework to do server-side rendering like [NextJS](https://nextjs.org/) can do the above thing pretty easily. [source](https://nextjs.org/docs/basic-features/data-fetching). I will do some research and let the team know since I am doing some research on architectural enhancements for the dashboard currently. umijs does not support it by default

**Comment by pravins** [comment]
This is fixed with https://github.com/distributed-system-analysis/pbench/pull/2871
