### ISSUE TITLE
Reducing bar clusters in comparison results in a "white screen of death"

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench-dashboard#2]
When selecting two fio runs to compare the dashboard goes "all white" and is unresponsive.  This failure happens in 3 different browsers (including Chrome).  The process to repeat this includes:

1) Pick the controller (highlighted in blue):
<img width="1663" alt="Screen Shot 2020-02-20 at 7 00 27 AM" src="https://user-images.githubusercontent.com/9037549/74936221-61001900-53af-11ea-9969-bbb7afe89de8.png">

2) Pick top two runs:
<img width="1677" alt="Screen Shot 2020-02-20 at 7 00 47 AM" src="https://user-images.githubusercontent.com/9037549/74936363-9a388900-53af-11ea-9802-327e3422f2b8.png">
...then select "compare results", and on the next page, select "compare iterations"

3) First remove all of the parameters from the cluster-config that don't result in reducing the number of clusters.  This is all of them *except* bs, rw, and size.  Clearing these does not reduce the number of clusters because all of these iterations have the exact same value for these params -(which BTW these params probably should not be shown at all within the cluster-config because "clearing" them does nothing,  and rendering them here only clutters the UI with unnecessary widgets).  FWIW, that step is not necessary to reproduce the problem, but it shows that clearing params which *don't* reduce the number of clusters is not the problem.  Finally, in this example, you are left with bs, rw, and size:
<img width="1681" alt="Screen Shot 2020-02-20 at 7 01 28 AM" src="https://user-images.githubusercontent.com/9037549/74936519-e1bf1500-53af-11ea-8305-ef9cdc060183.png">

4) Then click on the "rw" to clear it from the cluster-config.  You will get a "white screen of death" with no response.

**Comment by portante** [comment]
Seems like this would be easier to solve after https://github.com/distributed-system-analysis/pbench/pull/1401 is migrated and merged here.

**Comment by gurbirkalsi** [comment]
#7 aims to resolve this issue by utilizing the pbench-result-data-sample index. Once phase two has been merged, we will test to make sure clustering config changes update successfully within the run comparison page.

**Comment by gurbirkalsi** [comment]
Resolved with PR #41
