### ISSUE TITLE
Reference first_name in the put request for password recovery

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#211]
Currently the PUT api for updating user information needs two things: first_name and password (new password set by the user). Currently #123 just sends the newly selected password and the token from the email as a part of authorization header. 

We either would want to refactor the PUT api on  the server or find a way to reference first_name in the dashboard which can be sent in the PUT request

**Comment by webbnh** [comment]
Does the server really expect "first_name"?  Or, does it expect the _user_ name?  I _think_ that neither is required, as the user ID should be encoded in the authorization token.

**Comment by webbnh** [comment]
As I think about it, we probably should decouple the target of the reset from the authorization for the request:  otherwise, there would be no way for an admin to reset someone else's password....
