### ISSUE TITLE
all/most results generated with pbench-run-benchmark do not appear in the dashboard

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench-dashboard#3]

**Comment by portante** [comment]
When PR https://github.com/distributed-system-analysis/pbench/pull/1401 is migrated to this new repository, and merged, then `pbench-run-benchmark` results will start to appear in the dashboard ...

AFTER ... the pbench server starts to index them (see https://github.com/distributed-system-analysis/pbench/issues/1512).

**Comment by portante** [comment]
We don't use `pbench-run-benchmark` anymore.  Closing.
