### ISSUE TITLE
pbench system comparisons

### ISSUE THREAD

**Issue by gurbirkalsi** [distributed-system-analysis/pbench-dashboard#45]
Enhance the current run comparison workflow to provide system fact comparisons between workloads. Currently, `cloud.redhat.com` provides this feature via an app called Drift. This app provides comparison of  system facts like arch, bios_release_date, bios_vendor, bios_version, cloud_provider, cores_per_socket, cpu_flags,
enabled_services, fqdn, infrastructure_type, infrastructure_vendor, installed_packages, installed_services, kernel_modules, last_boot_time,
network_interfaces, number_of_cpus,  number_of_sockets, os_kernel_version, os_release, satellite_managed, system_memory, yum_repos.

For doing comparisons of configuration data relevant for performance, we'll want to extract a bit more configuration data from the sosreports (e.g. cpu type, tuned configuration, etc. etc.). The list of configuration information currently compared is at https://github.com/beav/kerlescan/blob/master/kerlescan/constants.py. The frontend for Drift can be found at https://github.com/RedHatInsights/drift-frontend. 

While enhancements are made to sosreport collection, we can implement a mocked component using PatternFly to visualize a system fact comparison.

**Comment by aquibbaig** [comment]
I made an initial design for the component and [this](https://www.figma.com/file/4ozRk6HWABeVPTGti35ov5/Pbench-system-comparisions?node-id=0%3A1) is what I could think of, need to discuss it with the team.
