### ISSUE TITLE
Mock the flow for providing a Public data view for an anonymous user

### ISSUE THREAD

**Issue by anishaswain** [distributed-system-analysis/pbench-dashboard#59]
We need to mock up a public data page which will be visible to the user even without logging in and will give the user visual feedback to login in order to access customised data.

![Screenshot (1)](https://user-images.githubusercontent.com/16955978/82637756-1ba7ed80-9c23-11ea-9c4c-e2910d38c25c.png)

The protoype: https://marvelapp.com/dh1cd91/screen/69487661

**Comment by aquibbaig** [comment]
@Anisha1234 This will be more like a guest session?
