### ISSUE TITLE
Update elasticsearch endpoints

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#72]
Currently, the endpoints we have in dashboard are fetching both run records and toc records, on which if we add a timestamp query, it fails. For example, the endpoint for fetching controllers `http://elasticsearch.perf.lab.eng.bos.redhat.com:9280/dsa-pbench.v3.run.2020-05,dsa-pbench.v3.run.2020-04/_search` needs to be replaced with `http://elasticsearch.perf.lab.eng.bos.redhat.com:9280/dsa-pbench.v3.run.2020-04,dsa-pbench.v3.run.2020-05,/pbench-run/_search?ignore_unavailable=true` to reflect only the run records and we can then use a timestamp sub aggregation on top of it to store timestamp fields of controllers in our redux store.

**Comment by portante** [comment]
No longer an issue for the dashboard, as the pbench-server APIs should handle this.
