### ISSUE TITLE
E2E test failing on Travis

### ISSUE THREAD

**Issue by anishaswain** [distributed-system-analysis/pbench-dashboard#91]
E2E test is failing in #86 
error message: `should change the selected dates after picking them from the calendar`

![share](https://user-images.githubusercontent.com/16955978/95051730-5a8a9b80-070b-11eb-9f71-6547e383fbc1.png)
Note: _The tests are passing in the local system_

**Comment by anishaswain** [comment]
@gurbirkalsi & @aquibbaig I already tried increasing the `timeout` and `slomo` for the search page. And the controller component is also throwing error which has not changed at all.

**Comment by aquibbaig** [comment]
So, it says that it couldn't find a specific selector for the date picker. What you can do is replace the appropriate selector from the DOM tree and replace here.

**Comment by anishaswain** [comment]
@aquibbaig I tried that as well. It's still failing on Travis while working fine in the local system. I guess @gurbirkalsi was also facing a similar issue with another PR. Plus, I don't think the changes for the controller e2e test should go in "Public data view" PR so we should create another PR if there is any bug in e2e tests.

**Comment by aquibbaig** [comment]
@gurbirkalsi @anishaswain  A few things that we can do about this. From my personal experience, I found 3 ways to deal with e2e tests.

Firstly, we need to comment out the `afterAll()` method in the e2e tests. That would stop the browser from closing after a test suit is complete.

1. First, we have to see if the element is visible or not. For that we add a simple javascript function in the console.
 as follows:
```
document.querySelectorAll(*css_selector*)
>>> if the output is an empty array, we'd conclude that the element is not visible.
```

2. Depending on the result from the earlier test, if the element is not visible for some reason, we can check which element is taking its place by adding an `onClick` event as a test as follows:
```

---
for any of the above tests, we can also use `puppeteer-recorder` which is a handy-dandy Chrome extension
---

document.addEventListener('click', (e) => console.log(e.target))
>>> check which element is clicked when we mouse click manually on the expect element
```

3. If none of the above tests work to fix the issue, the last way is to try out various puppeteer selector methods and check which of them works. (`page.$eval()`, `page.$()`, `page.$$()`, `page.$$eval()`, `page.evaluate()` etc.)

**Comment by gurbirkalsi** [comment]
+1 to @aquibbaig's recommended steps. In addition, Chrome Dev Tools allows you find the exact selector for an element by right clicking and copying a highlighted node's position in the tree.

**Comment by gurbirkalsi** [comment]
@anishaswain, did the rebase against PR #87 resolve this issue for you?

**Comment by anishaswain** [comment]
@gurbirkalsi yes it did.
