### ISSUE TITLE
fix security vulnerability of node-fetch

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#92]
currently, we see a severe error of potential security vulnerability of the module `node-fetch` by dependabot, which cant be automatically fixed it seems. So, if it is of some importance, we can either upgrade the dependency or we can ignore the warning manually.
```
Remediation

Upgrade node-fetch to version 2.6.1 or later. For example:

"dependencies": {
  "node-fetch": ">=2.6.1"
}

or…

"devDependencies": {
  "node-fetch": ">=2.6.1"
}


```

**Comment by portante** [comment]
Fixed by #93.
