### ISSUE TITLE
Unable to remove favorite records in the table

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench-dashboard#94]
Once we click on the `star` icon, we are able to favorite records to our redux store and also add them to a separate favorites panel. Once the icon is clicked, it gets disabled, i think the user would be able to remove a specific record from favorites as well.

**Comment by aquibbaig** [comment]
@gurbirkalsi @portante Since the user authentication work is in progress, do we still want to allow `non registered users` to favorite controllers and results, the other option is to allow only registered users to `star` records for future reference.

**Comment by portante** [comment]
To make it simple we should just do this for registered users.  Thoughts?

**Comment by aquibbaig** [comment]
@portante I also thought the same. We can display a modal "please register on Pbench dashboard to bookmark records"
