### ISSUE TITLE
Need of routing changes to incorporate addressable URLs

### ISSUE THREAD

**Issue by anishaswain** [distributed-system-analysis/pbench-dashboard#99]
Every URL entered directly by the user in the browser, needs to be addressable by both logged in and non-logged-in users. 
The dashboard needs to handle the URL in such a manner that, it will either invoke a particular change in data(or, display of certain elements) according to the existence of the user. Or, it will simply redirect the user to the log in screen.

**Comment by portante** [comment]
Work on this being done in #172.
